version: '3.8'

services:
  healthcare-dashboard:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: healthcare-api-dashboard
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - SECRET_KEY=production-secret-key-change-me
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - healthcare-network

  # Optional: Redis for caching (if you want to add caching later)
  redis:
    image: redis:7-alpine
    container_name: healthcare-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - healthcare-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: healthcare-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - healthcare-dashboard
    restart: unless-stopped
    networks:
      - healthcare-network

volumes:
  redis_data:

networks:
  healthcare-network:
    driver: bridge